Shton disa komanda te reja, Ilustron me shembuj, shton seksione te reja
xh3n1/git-al pull request #3
Opened 2018-11-25 13:28 UTC by klendi

2018-11-25 16:18 UTC, xh3n1 requested changes
Faleminderit @klendi, vetem nje typo edhe eshte super  :)   🎆

2018-11-25 16:18 UTC, xh3n1 commented on README.md
> +[Sharkoni](https://git-scm.com/downloads) git nga faqja zyrtare.
```suggestion
[Shkarkoni](https://git-scm.com/downloads) git nga faqja zyrtare.
```

2018-11-25 16:18 UTC, xh3n1 commented on README.md
> +[Sharkoni](https://git-scm.com/downloads) git nga faqja zyrtare.
typo ;)

2018-11-25 16:18 UTC, xh3n1 commented on README.md
> +<pre>git clone git@[url-depos]</pre>
Me mire repo se depo mendoj une ;)

2018-11-26 03:32 UTC, klendi commented on README.md
> +[Sharkoni](https://git-scm.com/downloads) git nga faqja zyrtare.
Po nuk ma ka zene syri fare. Gabim shpejtesie

2018-11-26 03:38 UTC, klendi commented on README.md
> +<pre>git clone git@[url-depos]</pre>
Varet, repo eshte me shume term ne anglisht. Nqs duam te kalojme shqip do na duhet ta quajme depo. Nejse kjo eshte preference personale. Un vendosa dy variante kur iu referoja repo-ve. "Repositories/depo". Ne menyre qe te kuptohet per cfare po flasim

2018-11-26 10:08 UTC, xh3n1 approved these changes

2018-11-26 10:08 UTC, merged